apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: amitbd1508/payment-service:1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables

            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-app-config
                  key: db_url

            - name: PAYMENT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: payment-app-config
                  key: payment_token

            - name: DB_PORT
              value: "3306"

            - name: SERVER_PORT
              value: "8080"

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: paymentdb-config
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: paymentdb-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: paymentdb-secrets
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-app-config
data:
  db_url: payment-db-service
  topic-name: topic
  payment_token: paymentttoken01sdfsdfs


---
apiVersion: v1
kind: Secret
metadata:
  name: payment-app-secret
type: Opaque
stringData:
  username: cm9vdA==
  password: MTk4Ng==
